name: Publish amazon-api-gateway

on:
  push:
    paths:
    - 'amazon-api-gateway/**'
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: |
        cd amazon-api-gateway/
        terraform init

    - name: Terraform destroy
      run: |
        cd amazon-cognito/
        terraform destroy
      
    # - name: Terraform plan
    #   run: |
    #     cd amazon-api-gateway/
    #     terraform plan
      
    # - name: Terraform apply
    #   run: |
    #     cd amazon-api-gateway/
    #     terraform apply -auto-approve
