name: Publish amazon-api-gateway

on:
  push:
    paths:
    - 'amazon-api-gateway/**'
    branches:
      - teste

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Terraform init
      run: terraform init
      
    - name: Terraform plan
      run: terraform plan
      
    - name: Terraform apply
      run: terraform apply -auto-approve
